// Audit for issue #79: diffs every spawned, opN=Attack .npc debugname against
// triggers.dropdata's coverage (direct debugname match, or category-resolved
// match) to find which player-killable NPCs still have no transcribed drop
// table for the /items "NPC Drop Sources" section (built by #57/#69).
//
// Read-only analysis - touches no .rs2 gameplay scripts and writes nothing
// back into the game data. Its only output is the committed
// content/scripts/drop tables/webdata/coverage-gap.md report below.
//
// Run from the engine/ package root: `npx tsx tools/audit/NpcDropCoverageGap.ts`
// Re-runnable: new NPCs/content can shift the numbers on later invocations,
// which is why the report notes the commit hash it was derived from.

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

import { loadAllNpcConfigs, loadDropTables, loadLabels, loadNpcNames, loadNpcSpawns, nearestLabel, resolveTriggerKey, type NpcConfig, type NpcLocation } from '#/util/ItemSourceIndex.js';

function gitCommit(cwd: string): string | null {
    try {
        return execSync('git rev-parse HEAD', { cwd, encoding: 'ascii' }).trim();
    } catch {
        return null;
    }
}

function areasFor(locations: NpcLocation[], labels: ReturnType<typeof loadLabels>): string[] {
    const areas = new Set<string>();
    for (const loc of locations) {
        const area = nearestLabel(labels, loc.x, loc.z);
        if (area) {
            areas.add(area);
        }
    }
    return [...areas].sort();
}

function main() {
    const npcConfigs = loadAllNpcConfigs();
    const npcNames = loadNpcNames();
    const npcSpawns = loadNpcSpawns(npcNames);
    const labels = loadLabels();
    const { triggers } = loadDropTables();

    // Union every trigger key's resolved debugname set (direct debugname keys
    // resolve to themselves; underscore-prefixed category keys resolve to
    // every .npc with a matching category= field) - this is the exact
    // resolution ItemSourceIndex.ts's live /items page uses, replayed here
    // rather than re-derived, so "covered" always means what the site means.
    const covered = new Set<string>();
    for (const triggerKey of triggers.keys()) {
        const resolved = resolveTriggerKey(triggerKey, npcConfigs);
        if (resolved) {
            for (const debugname of resolved.debugnames) {
                covered.add(debugname);
            }
        }
    }

    type Row = { debugname: string; name: string | null; spawnCount: number; areas: string[] };

    const attackableAndSpawned: Row[] = [];
    const unspawned: NpcConfig[] = [];

    for (const config of npcConfigs.values()) {
        if (!config.attackable) {
            continue;
        }

        const locations = npcSpawns.get(config.debugname) ?? [];
        if (locations.length === 0) {
            unspawned.push(config);
            continue;
        }

        attackableAndSpawned.push({
            debugname: config.debugname,
            name: config.name,
            spawnCount: locations.length,
            areas: areasFor(locations, labels)
        });
    }

    attackableAndSpawned.sort((a, b) => a.debugname.localeCompare(b.debugname));
    unspawned.sort((a, b) => a.debugname.localeCompare(b.debugname));

    const gap = attackableAndSpawned.filter(row => !covered.has(row.debugname));
    const coveredRows = attackableAndSpawned.filter(row => covered.has(row.debugname));

    const spotCheck = ['ardougne_archer', 'black_knight_titan', 'bat', 'arena_guard1', 'babydragon'];
    const gapNames = new Set(gap.map(r => r.debugname));
    const missingFromSpotCheck = spotCheck.filter(n => !gapNames.has(n));
    if (missingFromSpotCheck.length > 0) {
        console.error(`WARNING: spot-check debugnames NOT found in the gap list: ${missingFromSpotCheck.join(', ')}`);
    } else {
        console.log('Spot-check OK: all 5 expected debugnames are present in the gap list.');
    }

    // repo root = two levels up from engine/tools/audit/
    const repoRoot = path.resolve(import.meta.dirname, '..', '..', '..');
    const metaCommit = gitCommit(repoRoot);
    const contentCommit = gitCommit(path.join(repoRoot, 'content'));
    const engineCommit = gitCommit(path.join(repoRoot, 'engine'));

    const lines: string[] = [];
    lines.push('# NPC drop-data coverage gap (issue #79)');
    lines.push('');
    lines.push(
        'Diffs every spawned, `opN=Attack` NPC debugname (parsed from all `.npc` config files, including `_unpack/` dumps) against `triggers.dropdata` coverage - a direct debugname match, or a category match resolved the same way the live `/items` "NPC Drop Sources" section resolves it (`resolveTriggerKey()` in `engine/src/util/ItemSourceIndex.ts`). Generated by `engine/tools/audit/NpcDropCoverageGap.ts`; read-only, re-runnable - new NPCs/content can shift these numbers on a later run.'
    );
    lines.push('');
    lines.push('## Derived from');
    lines.push('');
    lines.push(`- Meta-repo (\`cboyd10/runescape\`) commit: \`${metaCommit ?? 'unknown'}\``);
    lines.push(`- \`content\` submodule commit: \`${contentCommit ?? 'unknown'}\``);
    lines.push(`- \`engine\` submodule commit: \`${engineCommit ?? 'unknown'}\``);
    lines.push('');
    lines.push('## Summary');
    lines.push('');
    lines.push(`- Attackable (\`opN=Attack\`) and spawned debugnames: **${attackableAndSpawned.length}**`);
    lines.push(`- Covered by \`triggers.dropdata\` (direct or category match): **${coveredRows.length}**`);
    lines.push(`- Gap (attackable, spawned, uncovered): **${gap.length}**`);
    lines.push(`- Attackable but unspawned (excluded from the gap, listed separately below): **${unspawned.length}**`);
    lines.push('');
    lines.push(
        `Spot-check: ${spotCheck.map(n => `\`${n}\``).join(', ')} ${missingFromSpotCheck.length === 0 ? 'all confirmed present in the gap list below.' : `- **MISSING from gap**: ${missingFromSpotCheck.map(n => `\`${n}\``).join(', ')} (see note above).`}`
    );
    lines.push('');
    lines.push('## Gap list');
    lines.push('');
    lines.push('Attackable, spawned, and not covered by any `triggers.dropdata` entry (direct or category-resolved).');
    lines.push('');
    lines.push('| Debugname | Name | Spawn count | Known area(s) |');
    lines.push('| --- | --- | ---: | --- |');
    for (const row of gap) {
        const name = row.name ?? '_(none)_';
        const areas = row.areas.length > 0 ? row.areas.join(', ') : '_(unresolved)_';
        lines.push(`| \`${row.debugname}\` | ${name} | ${row.spawnCount} | ${areas} |`);
    }
    lines.push('');
    lines.push('## Unspawned, skipped for now');
    lines.push('');
    lines.push('Attackable (`opN=Attack`) debugnames with zero spawn locations in the current map data - excluded from the gap above per issue #79\'s scope (out of scope: "NPCs that are attackable but currently unspawned").');
    lines.push('');
    lines.push('| Debugname | Name |');
    lines.push('| --- | --- |');
    for (const config of unspawned) {
        lines.push(`| \`${config.debugname}\` | ${config.name ?? '_(none)_'} |`);
    }
    lines.push('');

    const outPath = path.join(repoRoot, 'content', 'scripts', 'drop tables', 'webdata', 'coverage-gap.md');
    fs.writeFileSync(outPath, lines.join('\n'));

    console.log(`Wrote ${outPath}`);
    console.log(`attackable+spawned=${attackableAndSpawned.length} covered=${coveredRows.length} gap=${gap.length} unspawned=${unspawned.length}`);
}

main();
